import jsPDF from "jspdf";
import { autoTable } from "jspdf-autotable";
import type { MedicalReport } from "@/hooks/useMedicalReports";

const COLORS = {
  primary: [37, 99, 235] as [number, number, number],      // blue-600
  primaryLight: [239, 246, 255] as [number, number, number], // blue-50
  success: [22, 163, 74] as [number, number, number],       // green-600
  successBg: [240, 253, 244] as [number, number, number],   // green-50
  danger: [220, 38, 38] as [number, number, number],        // red-600
  dangerBg: [254, 242, 242] as [number, number, number],    // red-50
  warning: [234, 179, 8] as [number, number, number],       // yellow-500
  warningBg: [254, 252, 232] as [number, number, number],   // yellow-50
  dark: [30, 41, 59] as [number, number, number],           // slate-800
  muted: [100, 116, 139] as [number, number, number],       // slate-500
  border: [226, 232, 240] as [number, number, number],      // slate-200
  white: [255, 255, 255] as [number, number, number],
  bg: [248, 250, 252] as [number, number, number],          // slate-50
};

const STATUS_COLORS: Record<string, { text: [number, number, number]; bg: [number, number, number] }> = {
  normal: { text: COLORS.success, bg: COLORS.successBg },
  high: { text: COLORS.danger, bg: COLORS.dangerBg },
  low: { text: COLORS.primary, bg: COLORS.primaryLight },
  critical: { text: [153, 27, 27], bg: [254, 226, 226] },
};

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(15, pageH - 15, pageW - 15, pageH - 15);
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by MedVault • Confidential Medical Document", 15, pageH - 10);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 15, pageH - 10, { align: "right" });
}

export async function generateReportPdf(report: MedicalReport) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = 0;

  const data = report.extracted_data || {};
  const testResults = data.test_results || [];
  const medications = data.medications || [];
  const findings = data.findings || [];

  // Load logo
  const logoUrl = "/logo.png";
  let logoData: string | null = null;
  try {
    const response = await fetch(logoUrl);
    const blob = await response.blob();
    logoData = await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn("Failed to load logo", error);
  }

  // ─── Modern Header ───
  // Background Pattern
  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(0, 0, pageW, 45, "F");

  // Accent Line
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 2, "F");

  // Logo & Branding
  if (logoData) {
    doc.addImage(logoData, "PNG", margin, 12, 10, 10);
  }

  // App Name
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.primary);
  doc.text("My Health Compass", logoData ? margin + 14 : margin, 19);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.muted);
  doc.text("Your Personal Health Record", logoData ? margin + 14 : margin, 23);

  // Report Title & Meta (Right Aligned)
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.dark);
  doc.text("Medical Report", pageW - margin, 18, { align: "right" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.muted);
  const dateStr = report.report_date
    ? new Date(report.report_date).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })
    : "Date Not Specified";
  doc.text(dateStr, pageW - margin, 24, { align: "right" });

  // Divider
  doc.setDrawColor(...COLORS.border);
  doc.line(margin, 45, pageW - margin, 45);

  y = 55;

  // ─── Status Badge & Report Info ───
  // Report Title
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.dark);
  doc.text(report.title, margin, y);

  // Status Badge
  const statusColor = report.status === "completed" ? COLORS.success : COLORS.warning;
  doc.setFillColor(...statusColor);
  doc.roundedRect(pageW - margin - 22, y - 4, 22, 6, 1, 1, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.white);
  doc.text(report.status.toUpperCase(), pageW - margin - 11, y, { align: "center" });

  y += 8;

  // Metadata Grid
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(`Type: ${report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)}`, margin, y);
  if (data.lab_name) {
    doc.text(`Lab: ${data.lab_name}`, margin + 60, y);
  }
  doc.text(`Ref ID: #${report.id.slice(0, 8).toUpperCase()}`, pageW - margin, y, { align: "right" });

  y += 12;

  // ─── AI Summary Section ───
  if (report.ai_summary) {
    // Container
    doc.setDrawColor(219, 234, 254); // blue-100
    doc.setFillColor(239, 246, 255); // blue-50
    doc.roundedRect(margin, y, contentW, 8, 2, 2, "FD");

    // Icon & Title
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.primary);
    doc.text("AI Analysis Summary", margin + 4, y + 5.5);

    y += 12;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.dark);
    const summaryLines = doc.splitTextToSize(report.ai_summary, contentW - 8);

    // Left border for content emphasis
    doc.setDrawColor(...COLORS.primaryLight);
    doc.setLineWidth(1);
    doc.line(margin + 2, y, margin + 2, y + (summaryLines.length * 4.5));

    doc.text(summaryLines, margin + 6, y + 1);
    y += summaryLines.length * 4.5 + 10;
  }

  // ─── Quick Stats Bar (Modern) ───
  if (testResults.length > 0) {
    const abnormalCount = testResults.filter(
      (t: any) => t.status === "high" || t.status === "low" || t.status === "critical"
    ).length;
    const normalCount = testResults.length - abnormalCount;

    const statW = (contentW - 6) / 3; // Gap of 3
    const statsData = [
      { label: "Total Tests", value: String(testResults.length), color: COLORS.primary, bgColor: COLORS.primaryLight, icon: "📋" },
      { label: "Normal Results", value: String(normalCount), color: COLORS.success, bgColor: COLORS.successBg, icon: "✅" },
      { label: "Needs Attention", value: String(abnormalCount), color: abnormalCount > 0 ? COLORS.danger : COLORS.success, bgColor: abnormalCount > 0 ? COLORS.dangerBg : COLORS.successBg, icon: abnormalCount > 0 ? "⚠️" : "✨" },
    ];

    statsData.forEach((stat, i) => {
      const x = margin + i * (statW + 3);
      doc.setFillColor(...stat.bgColor);
      // Remove border for cleaner look
      doc.setDrawColor(...stat.bgColor);
      doc.roundedRect(x, y, statW, 18, 2, 2, "F");

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...stat.color);
      doc.text(stat.value, x + statW / 2, y + 8, { align: "center" });

      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COLORS.muted); // Muted label
      doc.text(stat.label.toUpperCase(), x + statW / 2, y + 14, { align: "center" });
    });
    y += 26;
  }

  // ─── Test Results Tables by Category ───
  if (testResults.length > 0) {
    const grouped = testResults.reduce((acc: Record<string, any[]>, test: any) => {
      const cat = test.category || "General Tests";
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(test);
      return acc;
    }, {});

    Object.entries(grouped).forEach(([category, tests]) => {
      // Check page break
      if (y > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        y = 20;
      }

      // Modern Category Header
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COLORS.dark);
      doc.text(category, margin, y + 5);

      // Underline
      doc.setDrawColor(...COLORS.border);
      doc.setLineWidth(0.2);
      doc.line(margin, y + 7, pageW - margin, y + 7);

      y += 10;

      const tableBody = (tests as any[]).map((test: any) => {
        const statusLabel = (test.status || "unknown").toUpperCase();
        return [
          test.test_name || "-",
          `${test.value || "-"}${test.unit ? ` ${test.unit}` : ""}`,
          test.reference_range || "-",
          statusLabel,
        ];
      });

      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [["TEST NAME", "RESULT", "REFERENCE RANGE", "STATUS"]],
        body: tableBody,
        theme: "grid", // Cleaner grid
        styles: {
          fontSize: 8,
          cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
          textColor: COLORS.dark,
          lineColor: COLORS.border,
          lineWidth: 0.1,
          font: "helvetica",
        },
        headStyles: {
          fillColor: COLORS.bg,
          textColor: COLORS.muted,
          fontStyle: "bold",
          fontSize: 7,
          halign: "left",
          lineWidth: 0, // No border for header
        },
        columnStyles: {
          0: { cellWidth: "auto", fontStyle: "bold" },
          1: { halign: "right", cellWidth: 35, fontStyle: "bold" },
          2: { halign: "center", cellWidth: 35, fontSize: 7, textColor: COLORS.muted },
          3: { halign: "center", cellWidth: 25, fontSize: 7, fontStyle: "bold" },
        },
        didParseCell: (hookData) => {
          if (hookData.section === "body" && hookData.column.index === 3) {
            const status = String(hookData.cell.raw).toLowerCase();
            const colors = STATUS_COLORS[status];
            if (colors) {
              hookData.cell.styles.textColor = colors.text;
              // Remove background for cleaner look, just colored text
              hookData.cell.styles.fillColor = [255, 255, 255];
            }
          }
          // Highlight abnormal result values directly
          if (hookData.section === "body" && hookData.column.index === 1) {
            const row = hookData.row.index;
            const testItem = (tests as any[])[row];
            if (testItem && (testItem.status === "high" || testItem.status === "critical")) {
              hookData.cell.styles.textColor = COLORS.danger;
            } else if (testItem && testItem.status === "low") {
              hookData.cell.styles.textColor = COLORS.primary;
            }
          }
        },
      });

      y = (doc as any).lastAutoTable.finalY + 12;
    });
  }

  // ─── Medications Section ───
  if (medications.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.dark);
    doc.text("Medications", margin, y + 5);
    doc.line(margin, y + 7, pageW - margin, y + 7);
    y += 10;

    const medBody = medications.map((med: any) => [
      med.name || "-",
      med.dosage || "-",
      med.frequency || "-",
      med.duration || "-",
      med.instructions || "-",
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["MEDICINE", "DOSAGE", "FREQUENCY", "DURATION", "INSTRUCTIONS"]],
      body: medBody,
      theme: "grid",
      styles: {
        fontSize: 8,
        cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
        textColor: COLORS.dark,
        lineColor: COLORS.border,
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: COLORS.warningBg,
        textColor: [161, 98, 7], // yellow-700
        fontStyle: "bold",
        fontSize: 7,
      },
      columnStyles: {
        0: { fontStyle: "bold" },
      },
    });

    y = (doc as any).lastAutoTable.finalY + 12;
  }

  // ─── Key Findings Section ───
  if (findings.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }

    // Card style for findings
    doc.setFillColor(...COLORS.successBg);
    doc.roundedRect(margin, y, contentW, 7, 1, 1, "F");

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.success);
    doc.text("Key Findings", margin + 3, y + 5);
    y += 10;

    findings.forEach((finding: string) => {
      if (y > doc.internal.pageSize.getHeight() - 25) {
        doc.addPage();
        y = 20;
      }
      doc.setFillColor(...COLORS.success);
      doc.circle(margin + 3, y - 1, 1.5, "F");

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.dark);

      const lines = doc.splitTextToSize(finding, contentW - 12);
      doc.text(lines, margin + 8, y);
      y += lines.length * 4.5 + 3;
    });
  }

  // ─── Footer on all pages ───
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  // ─── Save with cleaner name ───
  const safeName = report.title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 30);
  const dateSuffix = new Date().toISOString().split("T")[0];
  doc.save(`${safeName}_${dateSuffix}.pdf`);
}
