import jsPDF from "jspdf";
import { autoTable } from "jspdf-autotable";
import type { MedicalReport } from "@/hooks/useMedicalReports";

const COLORS = {
  primary: [37, 99, 235] as [number, number, number],      // blue-600
  primaryLight: [239, 246, 255] as [number, number, number], // blue-50
  success: [22, 163, 74] as [number, number, number],       // green-600
  successBg: [240, 253, 244] as [number, number, number],   // green-50
  danger: [220, 38, 38] as [number, number, number],        // red-600
  dangerBg: [254, 242, 242] as [number, number, number],    // red-50
  warning: [234, 179, 8] as [number, number, number],       // yellow-500
  warningBg: [254, 252, 232] as [number, number, number],   // yellow-50
  dark: [30, 41, 59] as [number, number, number],           // slate-800
  muted: [100, 116, 139] as [number, number, number],       // slate-500
  border: [226, 232, 240] as [number, number, number],      // slate-200
  white: [255, 255, 255] as [number, number, number],
  bg: [248, 250, 252] as [number, number, number],          // slate-50
};

const STATUS_COLORS: Record<string, { text: [number, number, number]; bg: [number, number, number] }> = {
  normal: { text: COLORS.success, bg: COLORS.successBg },
  high: { text: COLORS.danger, bg: COLORS.dangerBg },
  low: { text: COLORS.primary, bg: COLORS.primaryLight },
  critical: { text: [153, 27, 27], bg: [254, 226, 226] },
};

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(15, pageH - 15, pageW - 15, pageH - 15);
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by MedVault • Confidential Medical Document", 15, pageH - 10);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 15, pageH - 10, { align: "right" });
}

export function generateReportPdf(report: MedicalReport) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = 0;

  const data = report.extracted_data || {};
  const testResults = data.test_results || [];
  const medications = data.medications || [];
  const findings = data.findings || [];

  // ─── Header Banner ───
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 38, "F");

  // Decorative accent stripe
  doc.setFillColor(29, 78, 216); // blue-700
  doc.rect(0, 38, pageW, 2, "F");

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.white);
  doc.text("Medical Report", margin, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(191, 219, 254); // blue-200
  doc.text(report.title, margin, 26);

  // Right side meta
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.white);
  if (report.report_date) {
    doc.text(`Date: ${new Date(report.report_date).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`, pageW - margin, 14, { align: "right" });
  }
  const reportTypeLabel = report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1);
  doc.text(`Type: ${reportTypeLabel}`, pageW - margin, 20, { align: "right" });
  if (data.lab_name) {
    doc.text(`Lab: ${data.lab_name}`, pageW - margin, 26, { align: "right" });
  }
  doc.text(`ID: ${report.id.slice(0, 8).toUpperCase()}`, pageW - margin, 32, { align: "right" });

  y = 48;

  // ─── AI Summary Section ───
  if (report.ai_summary) {
    doc.setFillColor(...COLORS.primaryLight);
    doc.roundedRect(margin, y, contentW, 8, 1, 1, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.primary);
    doc.text("🤖  AI Summary", margin + 4, y + 5.5);
    y += 12;

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.dark);
    const summaryLines = doc.splitTextToSize(report.ai_summary, contentW - 8);
    doc.text(summaryLines, margin + 4, y + 1);
    y += summaryLines.length * 4 + 6;
  }

  // ─── Quick Stats Bar ───
  if (testResults.length > 0) {
    const abnormalCount = testResults.filter(
      (t: any) => t.status === "high" || t.status === "low" || t.status === "critical"
    ).length;
    const normalCount = testResults.length - abnormalCount;

    const statW = contentW / 3;
    const statsData = [
      { label: "Total Tests", value: String(testResults.length), color: COLORS.primary, bgColor: COLORS.primaryLight },
      { label: "Normal", value: String(normalCount), color: COLORS.success, bgColor: COLORS.successBg },
      { label: "Abnormal", value: String(abnormalCount), color: abnormalCount > 0 ? COLORS.danger : COLORS.success, bgColor: abnormalCount > 0 ? COLORS.dangerBg : COLORS.successBg },
    ];

    statsData.forEach((stat, i) => {
      const x = margin + i * statW;
      doc.setFillColor(...stat.bgColor);
      doc.roundedRect(x + 1, y, statW - 2, 16, 2, 2, "F");

      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...stat.color);
      doc.text(stat.value, x + statW / 2, y + 9, { align: "center" });

      doc.setFontSize(6.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.muted);
      doc.text(stat.label, x + statW / 2, y + 14, { align: "center" });
    });
    y += 22;
  }

  // ─── Test Results Tables by Category ───
  if (testResults.length > 0) {
    const grouped = testResults.reduce((acc: Record<string, any[]>, test: any) => {
      const cat = test.category || "General";
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(test);
      return acc;
    }, {});

    Object.entries(grouped).forEach(([category, tests]) => {
      // Check if we need a new page
      if (y > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        y = 20;
      }

      // Category header
      doc.setFillColor(...COLORS.dark);
      doc.roundedRect(margin, y, contentW, 7, 1, 1, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COLORS.white);
      doc.text(`  ${category}`, margin + 2, y + 5);
      y += 9;

      const tableBody = (tests as any[]).map((test: any) => {
        const statusLabel = (test.status || "unknown").toUpperCase();
        return [
          test.test_name || "-",
          `${test.value || "-"}${test.unit ? ` ${test.unit}` : ""}`,
          test.reference_range || "-",
          statusLabel,
        ];
      });

      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [["Test Name", "Result", "Reference Range", "Status"]],
        body: tableBody,
        theme: "plain",
        styles: {
          fontSize: 8,
          cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
          textColor: COLORS.dark,
          lineColor: COLORS.border,
          lineWidth: 0.2,
        },
        headStyles: {
          fillColor: COLORS.bg,
          textColor: COLORS.muted,
          fontStyle: "bold",
          fontSize: 7,
        },
        columnStyles: {
          0: { cellWidth: "auto", fontStyle: "bold" },
          1: { halign: "center", cellWidth: 35 },
          2: { halign: "center", cellWidth: 35, fontSize: 7, textColor: COLORS.muted },
          3: { halign: "center", cellWidth: 22, fontSize: 7 },
        },
        didParseCell: (hookData) => {
          if (hookData.section === "body" && hookData.column.index === 3) {
            const status = String(hookData.cell.raw).toLowerCase();
            const colors = STATUS_COLORS[status];
            if (colors) {
              hookData.cell.styles.textColor = colors.text;
              hookData.cell.styles.fillColor = colors.bg;
              hookData.cell.styles.fontStyle = "bold";
            }
          }
          // Highlight abnormal result values
          if (hookData.section === "body" && hookData.column.index === 1) {
            const row = hookData.row.index;
            const testItem = (tests as any[])[row];
            if (testItem && (testItem.status === "high" || testItem.status === "critical")) {
              hookData.cell.styles.textColor = COLORS.danger;
              hookData.cell.styles.fontStyle = "bold";
            } else if (testItem && testItem.status === "low") {
              hookData.cell.styles.textColor = COLORS.primary;
              hookData.cell.styles.fontStyle = "bold";
            }
          }
        },
      });

      y = (doc as any).lastAutoTable.finalY + 8;
    });
  }

  // ─── Medications Section ───
  if (medications.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(...COLORS.warning);
    doc.roundedRect(margin, y, contentW, 7, 1, 1, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.white);
    doc.text(`  💊 Medications (${medications.length})`, margin + 2, y + 5);
    y += 9;

    const medBody = medications.map((med: any) => [
      med.name || "-",
      med.dosage || "-",
      med.frequency || "-",
      med.duration || "-",
      med.instructions || "-",
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["Medicine", "Dosage", "Frequency", "Duration", "Instructions"]],
      body: medBody,
      theme: "plain",
      styles: {
        fontSize: 8,
        cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
        textColor: COLORS.dark,
        lineColor: COLORS.border,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: COLORS.warningBg,
        textColor: [113, 63, 18], // yellow-900
        fontStyle: "bold",
        fontSize: 7,
      },
      columnStyles: {
        0: { fontStyle: "bold" },
      },
    });

    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ─── Key Findings Section ───
  if (findings.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(...COLORS.success);
    doc.roundedRect(margin, y, contentW, 7, 1, 1, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.white);
    doc.text("  🔍 Key Findings", margin + 2, y + 5);
    y += 12;

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.dark);

    findings.forEach((finding: string) => {
      if (y > doc.internal.pageSize.getHeight() - 25) {
        doc.addPage();
        y = 20;
      }
      // Bullet
      doc.setFillColor(...COLORS.primary);
      doc.circle(margin + 3, y - 0.5, 1, "F");

      const lines = doc.splitTextToSize(finding, contentW - 12);
      doc.text(lines, margin + 7, y);
      y += lines.length * 4 + 3;
    });
  }

  // ─── Footer on all pages ───
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  // ─── Save ───
  const safeName = report.title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 40);
  doc.save(`${safeName}_Report.pdf`);
}
