import React from "react";
import { createRoot } from "react-dom/client";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";
import { MedicalReport } from "@/hooks/useMedicalReports";
import { processReportsForComparison } from "./healthDataUtils";
import { toast } from "sonner";
import HealthTrendsPDFView from "@/components/records/HealthTrendsPDFView";

export const downloadComparisonReport = async (reports: MedicalReport[]) => {
  if (reports.length === 0) return;

  try {
    const { sortedReports, comparisonItems, categories } = processReportsForComparison(reports);
    
    if (sortedReports.length === 0) {
      toast.error("No data available for export");
      return;
    }

    const pdf = new jsPDF("l", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let currentY = 20;

    // --- Header ---
    pdf.setFontSize(22);
    pdf.setTextColor(15, 23, 42);
    pdf.text("Health Comparison Analysis", 10, currentY);
    currentY += 8;
    
    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.text(`Patient health trends and interpretations generated on ${new Date().toLocaleDateString()}`, 10, currentY);
    currentY += 5;
    
    pdf.setDrawColor(226, 232, 240);
    pdf.line(10, currentY, pageWidth - 10, currentY);
    currentY += 10;

    // --- Summary Box ---
    pdf.setFillColor(248, 250, 252);
    pdf.setDrawColor(226, 232, 240);
    pdf.roundedRect(10, currentY, pageWidth - 20, 25, 2, 2, 'FD');
    
    pdf.setFontSize(12);
    pdf.setTextColor(30, 41, 59);
    pdf.text("AI Health Summary", 15, currentY + 7);
    
    pdf.setFontSize(9);
    pdf.setTextColor(71, 85, 105);
    pdf.text(`Based on ${sortedReports.length} records, your health metrics have been analyzed for trends and changes.`, 15, currentY + 13);
    pdf.text("Note: This summary evaluates metabolic markers and findings across your medical history.", 15, currentY + 18);
    
    currentY += 35;

    // --- Comparison Table ---
    const headers = [
      "Feature / Test Name",
      ...sortedReports.map(r => r.report_date ? new Date(r.report_date).toLocaleDateString(undefined, { day: '2-digit', month: 'short' }) : "New"),
      "Changes",
      "What this means"
    ];

    const body: any[] = [];
    categories.forEach(category => {
      // Category Header Row
      body.push([
        { content: category.toUpperCase(), colSpan: headers.length, styles: { fillColor: [241, 245, 249], fontStyle: 'bold', textColor: [37, 99, 235] } }
      ]);

      comparisonItems.filter(i => i.category === category).forEach(item => {
        const row = [
          `${item.name}${item.unit ? ` (${item.unit})` : ""}${item.reference_range ? `\nRef: ${item.reference_range}` : ""}`,
          ...item.values.map(v => v ? v.value : "—"),
          item.change === "initial" ? "Initial" : (item.percentChange ? `${parseFloat(item.percentChange) > 0 ? '+' : ''}${item.percentChange}%` : item.change),
          item.interpretation
        ];
        body.push(row);
      });
    });

    autoTable(pdf, {
      startY: currentY,
      head: [headers],
      body: body,
      theme: 'striped',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontSize: 9, halign: 'center' },
      columnStyles: {
        0: { cellWidth: 40, fontStyle: 'bold' },
        [headers.length - 2]: { halign: 'center', fontStyle: 'bold' },
        [headers.length - 1]: { cellWidth: 60, fontSize: 8 }
      },
      bodyStyles: { fontSize: 8, valign: 'middle' },
      margin: { left: 10, right: 10 },
      didDrawPage: (data) => {
        // Footer on each page
        pdf.setFontSize(8);
        pdf.setTextColor(148, 163, 184);
        pdf.text("Generated by E2Care Health | Confidential Report", 10, pageHeight - 10);
        pdf.text(`Page ${data.pageNumber}`, pageWidth - 20, pageHeight - 10);
      }
    });

    // --- Health Trends Section ---
    const trendsContainer = document.createElement("div");
    // Append to body but make it essentially invisible and pointer-events-none, but NOT display:none because it needs real dimensions
    trendsContainer.style.position = "absolute";
    trendsContainer.style.top = "0";
    trendsContainer.style.left = "-9999px";
    trendsContainer.style.width = "1000px";
    trendsContainer.style.zIndex = "-1";
    document.body.appendChild(trendsContainer);

    const root = createRoot(trendsContainer);
    // Use an async approach to ensure the React component cycle completes
    await new Promise<void>((resolve) => {
      root.render(
        React.createElement("div", { id: "pdf-health-trends-wrapper" },
          React.createElement(HealthTrendsPDFView, { reports })
        )
      );
      // Wait multiple frames for Recharts to evaluate container widths and paint
      setTimeout(resolve, 1500);
    });

    const trendViewElement = trendsContainer.querySelector("#pdf-health-trends") as HTMLElement;
    if (trendViewElement) {
      try {
        const canvas = await html2canvas(trendViewElement, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
          width: 1000,
          windowWidth: 1000,
        });

        const imgData = canvas.toDataURL("image/jpeg", 0.95); // JPEG is much smaller and faster for PDF standard reports
        const imgProps = pdf.getImageProperties(imgData);
        
        // Calculate dimensions to fit page width
        const availableWidth = pageWidth - 20;
        const imgHeight = (imgProps.height * availableWidth) / imgProps.width;

        pdf.addPage();
        
        // Header for new page
        pdf.setFontSize(22);
        pdf.setTextColor(15, 23, 42);
        pdf.text("Health Comparison Analysis", 10, 20);
        pdf.setFontSize(10);
        pdf.setTextColor(100, 116, 139);
        pdf.text(`Patient health trends visualization generated on ${new Date().toLocaleDateString()}`, 10, 28);
        pdf.setDrawColor(226, 232, 240);
        pdf.line(10, 33, pageWidth - 10, 33);
        
        // Render it scale-to-fit
        pdf.addImage(imgData, "JPEG", 10, 40, availableWidth, imgHeight);

        // Footer for new page
        pdf.setFontSize(8);
        pdf.setTextColor(148, 163, 184);
        pdf.text("Generated by E2Care Health | Confidential Report", 10, pageHeight - 10);
        pdf.text(`Page ${(pdf.internal as any).getNumberOfPages()}`, pageWidth - 20, pageHeight - 10);
      } catch (err) {
        console.error("Failed to snapshot HealthTrendsPDFView", err);
      }
    }

    // Cleanup
    root.unmount();
    document.body.removeChild(trendsContainer);

    pdf.save(`Health_Comparison_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success("Comparison report downloaded");
  } catch (error) {
    console.error("Error generating comparison report:", error);
    toast.error("Failed to generate report");
    throw error;
  }
};
